### ISSUE TITLE
Boostrap file ignored

### ISSUE THREAD

**Issue by willemstuursma** [ockcyp/covers-validator#1]
I saw your project on /r/php. Cool! We run into this issue every now and then and it would be great if we could have a fast check on the `@covers` annotations.

I installed your package using composer and then tried to run it with our configuration file as follows:

`./vendor/bin/covers-validator -c tests/phpunit.xml`.

However I does not seem to load the bootstrap file referenced the configuration XML file. Our autoloader is not included.

Our config file starts with:

````
<?xml version="1.0" encoding="UTF-8" ?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/4.4/phpunit.xsd"
		 backupGlobals="false"
		 backupStaticAttributes="false"
		 beStrictAboutTestsThatDoNotTestAnything="true"
		 bootstrap="./bootstrap.php"
		 colors="true">
	<php>
	...
````

Of course, this results in a class not found error, because our test cases extend from our own class (which extends from `PHPUnit_Framework_TestCase`).

**Comment by ockcyp** [comment]
Thanks for reporting this. I will fix it as soon as I can.

I guess for now you can copy `vendor/bin/covers-validator` and modify it to require your bootstrap file.

**Comment by ockcyp** [comment]
This has now been fixed

**Comment by willemstuursma** [comment]
Thanks. This works now, the bootstrap file is included now.
