### ISSUE TITLE
Issues with multiple test suites

### ISSUE THREAD

**Issue by willemstuursma** [ockcyp/covers-validator#3]
Hi, I have a `phpunit.xml` with multiple test suites:

````
	<testsuites>
		<testsuite name="Unit tests">
			<directory>../tests/unittests</directory>
		</testsuite>
		<testsuite name="Integration tests">
			<directory>../tests/integration</directory>
		</testsuite>
	</testsuites>
````

This results in an exception:

```
  [ReflectionException]
  Class Unit tests does not exist
````

It works fine, if I comment the second test suite away. I could not find any obvious uses of the Reflection API in your project, so I am not sure where this is coming from.

**Comment by ockcyp** [comment]
It's probably PHPUnit internals using reflection. I think I get those test suite names whilst looping over them. I'll have a look.

**Comment by willemstuursma** [comment]
Thanks!

**Comment by willemstuursma** [comment]
I justed wanted to express my appreciation for your hard work. Thanks! 

We are using this in our `build.xml`:

````
	<target name="check-coverage" description="Validate all @covers annotations">
		<exec executable="vendor/bin/covers-validator" failonerror="true">
			<redirector>
				<outputfilterchain>
					<linecontainsregexp negate="true">
						<regexp pattern="^Valid"/>
					</linecontainsregexp>
				</outputfilterchain>
			</redirector>
			<arg value="-c" />
			<arg file="${basedir}/build/phpunit.xml" />
		</exec>
	</target>
````

Maybe you can add it as an example to the documentation.

**Comment by ockcyp** [comment]
Good idea, I'll try to add phing and travis examples.

I guess it's also good idea to have a way of changing the program output.
It can get annoying to have list of all test cases when you have too many.
