### ISSUE TITLE
Heavy on dependencies

### ISSUE THREAD

**Issue by JeroenDeDauw** [ockcyp/covers-validator#4]
Adding this as a dependency causes all this stuff to be pulled in:

- ockcyp/covers-validator (v0.2.0)
- phpunit/phpunit (5.0.8)
- phpunit/php-code-coverage (3.0.1)
- phpunit/php-file-iterator (1.4.1)
- phpunit/php-token-stream (1.4.8)
- phpunit/php-timer (1.0.7)
- phpunit/phpunit-mock-objects (3.0.3)
- phpunit/php-text-template (1.2.1)
- phpspec/prophecy (v1.5.0)
- phpdocumentor/reflection-docblock (2.0.4)
- doctrine/instantiator (1.0.5)
- symfony/yaml (v2.7.6)
- sebastian/comparator (1.2.0)
- sebastian/diff (1.3.0)
- sebastian/environment (1.3.2)
- sebastian/exporter (1.2.1)
- sebastian/recursion-context (1.0.1)
- sebastian/global-state (1.1.1)
- sebastian/resource-operations (1.0.0)
- sebastian/version (1.0.6)
- myclabs/deep-copy (1.4.0)
- symfony/console (v2.7.6)

That triples the packages being pulled in for a lot of my projects. Can this not be avoided?

Thanks for creating this, much appreciated :)

**Comment by willemstuursma** [comment]
You should add it as a `require-dev` dependency. Most of this stuff are dependencies of PHPUnit.

**Comment by JeroenDeDauw** [comment]
> You should add it as a require-dev dependency.

That is what I am doing :)

**Comment by ockcyp** [comment]
20 of those packages are dependency of PHPUnit, I guess you don't have PHPUnit as a dependency in ``composer.json``. Would you prefer a PHAR build for the command?

**Comment by JeroenDeDauw** [comment]
That could help yes. However, do you really need all of PHPUnit for this covers validation to work? And if not, where is stuff going wrong - in the PHPUnit package itself?

Anyway, you can haz your first public dependents: https://packagist.org/packages/ockcyp/covers-validator/dependents

**Comment by ockcyp** [comment]
I don't need all of it but I use PHPUnit_Util_Configuration, PHPUnit_Framework_TestSuite, etc. which are in the [phpunit/phpunit](https://packagist.org/packages/phpunit/phpunit) package. I'll try adding PHAR build for the next release.

Btw, I love the way you organised the CI stuff on those projects.

**Comment by ockcyp** [comment]
@JeroenDeDauw Here's a PHAR release: https://github.com/ockcyp/covers-validator/releases/download/v0.3.0/covers-validator.phar

Let me know if you have any issues

**Comment by JeroenDeDauw** [comment]
I guess this can be close then :)

**Comment by ockcyp** [comment]
Okay, let me know if you have any issues with the PHAR release.
