### ISSUE TITLE
Recommended version range

### ISSUE THREAD

**Issue by JeroenDeDauw** [ockcyp/covers-validator#6]
Should I be using `~0.3.0`, or is it safe to do `~0.3`, in projects that only execute `vendor/bin/covers-validator` with no further arguments?

**Comment by ockcyp** [comment]
I might change the output to remove the valid lines but exit code will stay the same. Assuming you are using the exit code, feel free to use ``~0.3``.

**Comment by JeroenDeDauw** [comment]
The output is rather verbose yes. Perhaps only show that when passing `-v`? Outputting a bunch of dots like PHPUnit and PHPCS do by default would be nice.

**Comment by JeroenDeDauw** [comment]
Thanks for the quick reply!

**Comment by ockcyp** [comment]
yeah perhaps using verbosity settings will be easy to implement as a start.

You're welcome!
